language: node_js

node_js:
  - '10'

before_script:
  - npm install codecov -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test -- --coverage

after_success:
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - |
    echo "${TRAVIS_PULL_REQUEST}"
    echo "${TRAVIS_TAG}"
    if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]
    then
       if [[ "${TRAVIS_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
       then
          sed -ir "s/\"commit\": null/\"commit\": \"${TRAVIS_COMMIT}\"/I" package.json
          tsc
          npm install -g npm-cli-login
          npm-cli-login -u "${NPM_LOGIN}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
          npm publish --access public
       fi
    fi
